name: "build"
on: [push]

env:
  EM_VERSION: 2.0.34
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Verify
        run: emcc -v
      - name: Configure
        run: |
          mkdir build
          cd build
          emcmake cmake                                          \
                    -DCMAKE_BUILD_TYPE:STRING=Release            \
                    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON             \
                    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=ON \
                    -DCMAKE_POLICY_DEFAULT_CMP0069:STRING=NEW    \
                    ..
          emcc \
            -Oz \
            -flto \
            -fsanitize=undefined \
            -s SINGLE_FILE=1 \
            -s WASM_ASYNC_COMPILATION=0 \
            -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "getValue"]' \
            -s EXPORTED_FUNCTIONS='["_malloc", "_read", "_gme_open_data", "_gme_start_track", "_gme_track_ended", "_gme_track_count", "_gme_enable_accuracy", "_gme_play"]' \
            --extern-pre-js ../js/gme-pre.js \
            --extern-post-js ../js/gme-post.js \
            -o gme.js \
            gme/libgme.a
      - name: Build
        run: |
          cd build
          make
